language: node_js
node_js:
  - '8'
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn test
before_deploy:
  - yarn global add travis-ci-cloudfront-invalidation
  - yarn run build
deploy:
  provider: s3
  access_key_id: --
  secret_access_key: --
  bucket: awsprofessionalwebsite.com
  skip_cleanup: true
  local-dir: dist
  on:
    branch: master
after_deploy:
  - travis-ci-cloudfront-invalidation -a ACCESSID -s KEY -c E1GHFTFCK1XTDL -i '/*' -b $TRAVIS_BRANCH -p $TRAVIS_PULL_REQUEST
